//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parakeet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgressEntry
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public int TaskId { get; set; }
        public int AssociatedUserId { get; set; }
        public int ReportingUserId { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual User ProgressingMember { get; set; }
        public virtual User ReportingMember { get; set; }
    }
}
