//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parakeet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Query
    {
        public Query()
        {
            this.Users = new HashSet<User>();
            this.Tags = new HashSet<Tag>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
