//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parakeet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.Tags = new HashSet<Tag>();
            this.Children = new HashSet<Task>();
            this.Comments = new HashSet<Comment>();
            this.MentionedIn = new HashSet<Comment>();
            this.ProgressEntries = new HashSet<ProgressEntry>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual User AssignedUser { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
        public virtual ICollection<Task> Children { get; set; }
        public virtual Task Parent { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Comment> MentionedIn { get; set; }
        public virtual ICollection<ProgressEntry> ProgressEntries { get; set; }
    }
}
