//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parakeet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Roles = new HashSet<Role>();
            this.Queries = new HashSet<Query>();
            this.Comments = new HashSet<Comment>();
            this.MentionedIn = new HashSet<Comment>();
            this.AssociatedEntries = new HashSet<ProgressEntry>();
            this.ReportedEntries = new HashSet<ProgressEntry>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<Query> Queries { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Comment> MentionedIn { get; set; }
        public virtual ICollection<ProgressEntry> AssociatedEntries { get; set; }
        public virtual ICollection<ProgressEntry> ReportedEntries { get; set; }
    }
}
